#!/bin/bash
#======================================================================================
# Configure an instance of Ubuntu Linux to support basic programming training using
# Racket and AppInventor.
#
# Arguments:
# (None)		
#
# Version: 0.2.0
# Date: 06 Nov 2015
# Author: Dave Nicolette
#======================================================================================
export INSTALL_DIR="$HOME/provision-racket-ubuntu"
export COMMON_DIR="provision-ubuntu-common"

git clone "git://github.com/neopragma/$COMMON_DIR"

# Apply desktop tweaks for improved user experience

"./$COMMON_DIR/ubuntu_desktop_tweaks"

RESOURCES="$(pwd)/resources"

# Set the desktop background image

echo 
echo '============================================================='
echo 'Setting the desktop background image'
mkdir -p "$HOME/.local/backgrounds"
cp "$RESOURCES/racket-background.png" "$HOME/.local/backgrounds/."
gsettings set org.gnome.desktop.background picture-uri file:///home/racket/.local/backgrounds/racket-background.png

# Copy help files to the desktop

echo
echo '============================================================='
echo 'Copying help files to the desktop'
cp "$RESOURCES/tips-and-hints.html" "$HOME/Desktop"
cp -r "$RESOURCES/.images" "$HOME/Desktop/."

# Unpack preconfigured Firefox files

echo 
echo '============================================================='
echo 'Configuring Firefox...'
tar -zxvf "$RESOURCES/.mozilla" -C /home/racket

# Install Racket

echo
echo '============================================================='
echo 'Downloading Racket'
wget -c http://mirror.racket-lang.org/installers/recent/racket-6.2.1-x86_64-linux-ubuntu-precise.sh -O racket-6.2.1-x86_64-linux-ubuntu-precise.sh

mkdir -p "$HOME/bin"
test -f "$HOME/.bashrc-orig" || cp "$HOME/.bashrc" "$HOME/.bashrc-orig"
echo "export PATH=$PATH:/home/racket/bin" >> "$HOME/.bashrc"

echo
echo '============================================================='
echo '>>>> Racket interactive installer <<<<'
echo 'When prompted, reply as follows:'
echo
echo 'When asked for an administrator password...'
echo '  Reply: racket'
echo
echo 'Do you want a Unix-style distribution?'
echo '  Reply: no'
echo
echo 'Where do you want to install the "racket" directory tree?'
echo '  Reply: 3 (that is, ~/racket)'
echo
echo 'If you want to install new system links...'
echo '  Reply: /home/racket'

sh racket-6.2.1-x86_64-linux-ubuntu-precise.sh
sudo cp "$RESOURCES/drracket.desktop" /usr/share/applications/.
sudo cp "$RESOURCES/drracket.png" /usr/share/pixmaps/.

# Install AppInventor

echo
echo '============================================================='
echo 'Downloading AppInventor installer'
wget -c http://commondatastorage.googleapis.com/appinventordownloads/appinventor2-setup_1.1_all.deb -O appinventor2-setup_1.1_all.deb

echo
echo '============================================================='
echo 'Installing AppInventor and dependencies'
sudo dpkg -i *.deb
sudo apt-get -y install libc6-i386
sudo apt-get -y install zlib1g:i386

echo
echo '============================================================='
echo 'Configuring scripts, desktop files and icons for AppInventor aiStarter'
cp "$RESOURCES/aistop" "$HOME/bin/aistop"
chmod +x "$HOME/bin/aistop"
sudo cp "$RESOURCES/aistarter.desktop" /usr/share/applications/.
sudo cp "$RESOURCES/aistop.desktop" /usr/share/applications/.
sudo cp "$RESOURCES/android-icon.png" /usr/share/pixmaps/.
sudo cp "$RESOURCES/android-icon-red.png" /usr/share/pixmaps/.
test -f "$HOME/.bashrc-orig" || cp "$HOME/.bashrc" "$HOME/.bashrc-orig"
mkdir -p "$HOME/bin"
echo "export PATH=$PATH:$HOME/bin" >> "$HOME/.bashrc"

echo
echo '============================================================='
echo 'Locking favorite applications to the Unity Launcher'
gsettings set com.canonical.Unity.Launcher favorites "['application://org.gnome.Nautilus.desktop', 'application://firefox.desktop', 'application://drracket.desktop', 'application://aistarter.desktop', 'application://aistop.desktop', 'application://gnome-terminal.desktop']"




